// Generated by gencpp from file dual_robot_msgs/GraspWireRequest.msg
// DO NOT EDIT!


#ifndef DUAL_ROBOT_MSGS_MESSAGE_GRASPWIREREQUEST_H
#define DUAL_ROBOT_MSGS_MESSAGE_GRASPWIREREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>

namespace dual_robot_msgs
{
template <class ContainerAllocator>
struct GraspWireRequest_
{
  typedef GraspWireRequest_<ContainerAllocator> Type;

  GraspWireRequest_()
    : robot()
    , wire_grasp_pose()
    , pull_vec()  {
    }
  GraspWireRequest_(const ContainerAllocator& _alloc)
    : robot(_alloc)
    , wire_grasp_pose(_alloc)
    , pull_vec(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_type;
  _robot_type robot;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _wire_grasp_pose_type;
  _wire_grasp_pose_type wire_grasp_pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pull_vec_type;
  _pull_vec_type pull_vec;





  typedef boost::shared_ptr< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspWireRequest_

typedef ::dual_robot_msgs::GraspWireRequest_<std::allocator<void> > GraspWireRequest;

typedef boost::shared_ptr< ::dual_robot_msgs::GraspWireRequest > GraspWireRequestPtr;
typedef boost::shared_ptr< ::dual_robot_msgs::GraspWireRequest const> GraspWireRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator1> & lhs, const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot == rhs.robot &&
    lhs.wire_grasp_pose == rhs.wire_grasp_pose &&
    lhs.pull_vec == rhs.pull_vec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator1> & lhs, const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3e900c1a0ccd81f3f0298393d52c5aa";
  }

  static const char* value(const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3e900c1a0ccd81fULL;
  static const uint64_t static_value2 = 0x3f0298393d52c5aaULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_robot_msgs/GraspWireRequest";
  }

  static const char* value(const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot\n"
"geometry_msgs/Pose wire_grasp_pose \n"
"geometry_msgs/Vector3 pull_vec\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.wire_grasp_pose);
      stream.next(m.pull_vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspWireRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_robot_msgs::GraspWireRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot);
    s << indent << "wire_grasp_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.wire_grasp_pose);
    s << indent << "pull_vec: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pull_vec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ROBOT_MSGS_MESSAGE_GRASPWIREREQUEST_H
