// Generated by gencpp from file dual_robot_msgs/GraspObject.msg
// DO NOT EDIT!


#ifndef DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECT_H
#define DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECT_H

#include <ros/service_traits.h>


#include <dual_robot_msgs/GraspObjectRequest.h>
#include <dual_robot_msgs/GraspObjectResponse.h>


namespace dual_robot_msgs
{

struct GraspObject
{

typedef GraspObjectRequest Request;
typedef GraspObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspObject
} // namespace dual_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dual_robot_msgs::GraspObject > {
  static const char* value()
  {
    return "12262fe8f8c7e2294f69e77ba46a1d34";
  }

  static const char* value(const ::dual_robot_msgs::GraspObject&) { return value(); }
};

template<>
struct DataType< ::dual_robot_msgs::GraspObject > {
  static const char* value()
  {
    return "dual_robot_msgs/GraspObject";
  }

  static const char* value(const ::dual_robot_msgs::GraspObject&) { return value(); }
};


// service_traits::MD5Sum< ::dual_robot_msgs::GraspObjectRequest> should match
// service_traits::MD5Sum< ::dual_robot_msgs::GraspObject >
template<>
struct MD5Sum< ::dual_robot_msgs::GraspObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dual_robot_msgs::GraspObject >::value();
  }
  static const char* value(const ::dual_robot_msgs::GraspObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dual_robot_msgs::GraspObjectRequest> should match
// service_traits::DataType< ::dual_robot_msgs::GraspObject >
template<>
struct DataType< ::dual_robot_msgs::GraspObjectRequest>
{
  static const char* value()
  {
    return DataType< ::dual_robot_msgs::GraspObject >::value();
  }
  static const char* value(const ::dual_robot_msgs::GraspObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dual_robot_msgs::GraspObjectResponse> should match
// service_traits::MD5Sum< ::dual_robot_msgs::GraspObject >
template<>
struct MD5Sum< ::dual_robot_msgs::GraspObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dual_robot_msgs::GraspObject >::value();
  }
  static const char* value(const ::dual_robot_msgs::GraspObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dual_robot_msgs::GraspObjectResponse> should match
// service_traits::DataType< ::dual_robot_msgs::GraspObject >
template<>
struct DataType< ::dual_robot_msgs::GraspObjectResponse>
{
  static const char* value()
  {
    return DataType< ::dual_robot_msgs::GraspObject >::value();
  }
  static const char* value(const ::dual_robot_msgs::GraspObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECT_H
