// Generated by gencpp from file dual_robot_msgs/GraspObjectResponse.msg
// DO NOT EDIT!


#ifndef DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECTRESPONSE_H
#define DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_robot_msgs
{
template <class ContainerAllocator>
struct GraspObjectResponse_
{
  typedef GraspObjectResponse_<ContainerAllocator> Type;

  GraspObjectResponse_()
    : status(false)  {
    }
  GraspObjectResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GraspObjectResponse_

typedef ::dual_robot_msgs::GraspObjectResponse_<std::allocator<void> > GraspObjectResponse;

typedef boost::shared_ptr< ::dual_robot_msgs::GraspObjectResponse > GraspObjectResponsePtr;
typedef boost::shared_ptr< ::dual_robot_msgs::GraspObjectResponse const> GraspObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator1> & lhs, const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator1> & lhs, const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_robot_msgs/GraspObjectResponse";
  }

  static const char* value(const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status \n"
;
  }

  static const char* value(const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_robot_msgs::GraspObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ROBOT_MSGS_MESSAGE_GRASPOBJECTRESPONSE_H
