// Generated by gencpp from file wire_modeling_msgs/ProcessPointCloud.msg
// DO NOT EDIT!


#ifndef WIRE_MODELING_MSGS_MESSAGE_PROCESSPOINTCLOUD_H
#define WIRE_MODELING_MSGS_MESSAGE_PROCESSPOINTCLOUD_H

#include <ros/service_traits.h>


#include <wire_modeling_msgs/ProcessPointCloudRequest.h>
#include <wire_modeling_msgs/ProcessPointCloudResponse.h>


namespace wire_modeling_msgs
{

struct ProcessPointCloud
{

typedef ProcessPointCloudRequest Request;
typedef ProcessPointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessPointCloud
} // namespace wire_modeling_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wire_modeling_msgs::ProcessPointCloud > {
  static const char* value()
  {
    return "a037fc9cae4c4c70c78fcfe3985c54fd";
  }

  static const char* value(const ::wire_modeling_msgs::ProcessPointCloud&) { return value(); }
};

template<>
struct DataType< ::wire_modeling_msgs::ProcessPointCloud > {
  static const char* value()
  {
    return "wire_modeling_msgs/ProcessPointCloud";
  }

  static const char* value(const ::wire_modeling_msgs::ProcessPointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::wire_modeling_msgs::ProcessPointCloudRequest> should match
// service_traits::MD5Sum< ::wire_modeling_msgs::ProcessPointCloud >
template<>
struct MD5Sum< ::wire_modeling_msgs::ProcessPointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wire_modeling_msgs::ProcessPointCloud >::value();
  }
  static const char* value(const ::wire_modeling_msgs::ProcessPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wire_modeling_msgs::ProcessPointCloudRequest> should match
// service_traits::DataType< ::wire_modeling_msgs::ProcessPointCloud >
template<>
struct DataType< ::wire_modeling_msgs::ProcessPointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::wire_modeling_msgs::ProcessPointCloud >::value();
  }
  static const char* value(const ::wire_modeling_msgs::ProcessPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wire_modeling_msgs::ProcessPointCloudResponse> should match
// service_traits::MD5Sum< ::wire_modeling_msgs::ProcessPointCloud >
template<>
struct MD5Sum< ::wire_modeling_msgs::ProcessPointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wire_modeling_msgs::ProcessPointCloud >::value();
  }
  static const char* value(const ::wire_modeling_msgs::ProcessPointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wire_modeling_msgs::ProcessPointCloudResponse> should match
// service_traits::DataType< ::wire_modeling_msgs::ProcessPointCloud >
template<>
struct DataType< ::wire_modeling_msgs::ProcessPointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::wire_modeling_msgs::ProcessPointCloud >::value();
  }
  static const char* value(const ::wire_modeling_msgs::ProcessPointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIRE_MODELING_MSGS_MESSAGE_PROCESSPOINTCLOUD_H
